/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guideSidebar: [{ type: 'autogenerated', dirName: 'guide'}],

  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial'}],
  /*
  tutorialSidebar: ['intro',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [ { type: 'autogenerated', dirName: 'tutorial-basics'}]
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: []
    },
  ],
  */
  // apiSidebar: [ { type: 'autogenerated', dirName: 'api'}],
  apiSidebar: [ { type: 'category', label: 'GitDocumentDB', items: [
    'api/git-documentdb.gitdocumentdb',
    'api/git-documentdb.gitdocumentdb._constructor_',
    'api/git-documentdb.gitdocumentdb.author',
    'api/git-documentdb.gitdocumentdb.close',
    'api/git-documentdb.gitdocumentdb.collection',
    'api/git-documentdb.gitdocumentdb.committer',
  ]}],
  // But you can create a sidebar manually

/*  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],*/
};
